### ISSUE TITLE
Atom randomly crashing in MacOs Catalina

### ISSUE THREAD

**Issue by jagcon74** [tomszink/underline#4]
Hello All,

I've noticed and its happened a few times where I was working on a text file and suddenly boom it closes out on me.  I then reopen and continue.  sometimes I can reopen and continue. other times it takes 2 or 3 times of this cycle before I can resume.  i sometimes right click on mouse to invoke menu to do a save and it might be possible this might be triggering it, but can't confirm for sure.  Just wanted to mention this to all involved.   I am running the latest available code.   I upgraded within the last week or so to MacOS Catalina per the direction of my IT department and that is when I started noticing this happen.

Regards,
Jose

**Comment by tomszink** [comment]
Hi Jose (@jagcon74) , 
is sounds like a general issue with atom.io (and frankly, I also experience that sometimes : O )
So in this case, you have to report this to the atom repo.
This repo here is just a little plugin ("underline", to underline headlines for .rst).
With best regards,
Toms
